### ISSUE TITLE
Support GHC 8

### ISSUE THREAD

**Issue by 3noch** [haskell-distributed/distributed-process-client-server#5]
I may be doing something wrong, but I'm having trouble getting this to build with GHC 8.

**Comment by qnikst** [comment]
Hello, currently this package in not actively maintained by it's primary maintainer. I'll try to take a look into this issue but I can't guarantee that I'll do that promptly.

**Comment by 3noch** [comment]
@qnikst Thanks so much! I actually figured out the issue. It was my fault. 

On a side note, is this package safe to rely on for the future without a primary maintainer?

**Comment by qnikst** [comment]
Major bugs will be fixed but may be not very promptly. All PRs will be reviewed and merged possibly with delays. Versions bounds will be updated upon a notice. Unless somebody will volunteer to drive this package forward you should not expect much improvements. I'm not sure that I can say that I totally trust codebase so possibly there is a room for improvement , but as far as I know there are some users of this package and it works for them.
I think such situation will stay at least in the middle term.

**Comment by qnikst** [comment]
What I've written is only about distributed process platform packages like extras, client-sever. Network transport family, distributed-process itself and d-p-asynx are properly maintained.

**Comment by 3noch** [comment]
Ok thanks so much for this detail. I'm very, very new to the cloud haskell world. How critical is this package to the cloud haskell effort?

**Comment by 3noch** [comment]
Perhaps this is all documented somewhere so forgive me if I'm asking for info that is readily available.

**Comment by qnikst** [comment]
In our practice we primarily use distributed-process, network-transport-tcp, network-transport-inmemory, distributed-process-async, and build our primitives on top. There are also distributed-process-platform with a number of packages inside that try to mimic Erlang's OTR, they are not critical for writing code.

**Comment by 3noch** [comment]
Thanks very much. I'll close this issue since GHC 8 support is already working.

**Comment by hyperthunk** [comment]
Sorry, I'm trying to get back to maintaining these packages but have not had access to a working environment for quite some time now. Hopefully will be back on board soon but efforts to get back to the project stalled last year.

**Comment by hyperthunk** [comment]
@3noch please ping me if you need any assistance, this package is getting proper attention at last!
